//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalleEntity
    {
        private int ID { get; set; }
        public string Libelle { get; protected set; }
        public string Code { get; protected set; }
    }
}
